server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/receipt
    username: db-user
    password: db-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql: false
        format_sql: false
        show_sql: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
cache:
  is_active: true
  capacity: 10

